### ISSUE TITLE
CSL errors

### ISSUE THREAD

**Issue by Pourov** [Pourov/CSL-erros#1]
[WARN] [3 BG] 01:02:38.025 : PathUnit was not saved collectly. Segment[27383] on Transport[217]([20T] ポール市 沈没 プラザ #23 - ポール市地下鉄の駅 - Arayamae]
[WARN] [3 BG] 01:02:38.057 : PathUnit was not saved collectly. Segment[19430] on Transport[220]([30AD] ポール市ビーチバレー コート #1 - 構成レストラン桟橋]
[WARN] [3 BG] 01:02:38.115 : PathUnit was not saved collectly. Segment[15436] on Transport[231](TRANSPORT_LINE_PATTERN[Evacuation Bus]:0]
[WARN] [3 BG] 01:02:49.469 : No Segment: Transport[126] Node[18355]
[WARN] [3 BG] 01:02:49.469 : No Segment: Transport[145] Node[15275]
[WARN] [3 BG] 01:02:49.470 : No Segment: Transport[145] Node[15278]
[WARN] [3 BG] 01:02:49.470 : No Segment: Transport[170] Node[27971]
[WARN] [3 BG] 01:02:49.470 : No Segment: Transport[170] Node[27816]
[WARN] [3 BG] 01:02:49.470 : No Segment: Transport[170] Node[27814]
[WARN] [3 BG] 01:02:49.471 : No Segment: Transport[244] Node[9472]
[WARN] [3 BG] 01:02:51.903 : Transport[126]([12L] 芳琉ー地区 - ポール市地下鉄の駅 - Hamamaguchi) had errors on route path.
[WARN] [3 BG] 01:02:51.952 : Transport[145]([8-h] 芳琉ー地区 - [X=-5386.457|Y=167.4807|Z=-2277.64]) had errors on route path.
[WARN] [3 BG] 01:02:52.012 : Transport[170]([23-w] 牛潟ー地区 - ポール市地下鉄の駅 - Sumeira) had errors on route path.
[WARN] [3 BG] 01:02:52.218 : Transport[244]([24-x] 場ブラー地区 - ポール市地下鉄の駅 - 場部羅) had errors on route path.
[ERROR] [6 BG] 01:02:53.882 : System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at CSLMod.CSLMapView.Wpfgui.Drawing.Transports.TransportMapBuilder.BuildMap(XMLForTransport xml, TransportManager mgr)
   at CSLMod.CSLMapView.Wpfgui.Drawing.ImageSourceBuilder.<>c__DisplayClass4_0.<InvokeBuildAndAttach>b__7()
[ERROR] [4 BG] 01:02:54.079 : System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at CSLMod.CSLMapView.Wpfgui.Drawing.Transports.TransportMapBuilder.BuildMap(XMLForTransport xml, TransportManager mgr)
   at CSLMod.CSLMapView.Wpfgui.Drawing.ImageSourceBuilder.<>c__DisplayClass4_0.<InvokeBuildAndAttach>b__6()

**Comment by Pourov** [comment]
These are the warnings and error that I have recieved.
